[
{
"cve_id": "CVE-2024-22194",
"patch_date": [
"2023-12-22 15:13:59-05:00",
"2023-12-22 15:26:12-05:00",
"2023-12-22 14:43:22-05:00",
"2023-12-22 14:13:18-05:00",
"2023-12-22 16:20:49-05:00",
"2023-12-20 18:03:56-05:00",
"2023-12-22 13:12:57-05:00",
"2023-12-22 11:02:52-05:00",
"2023-12-22 10:32:55-05:00"
],
"patch_files": [
"case_utils/case_file/__init__.py",
"tests/lib/.gitignore",
"tests/case_utils/case_validate/uco_test_examples/Makefile",
"case_utils/case_sparql_select/__init__.py",
"setup.cfg",
".pre-commit-config.yaml",
"tests/Makefile",
"case_utils/local_uuid.py",
".github/workflows/cicd.yml",
"tests/case_utils/case_file/Makefile",
"case_utils/__init__.py",
"tests/lib/rdf-toolkit.jar.sha512",
"case_utils/case_sparql_construct/__init__.py",
"tests/case_utils/case_validate/cli/Makefile",
"tests/case_utils/case_validate/case_test_examples/Makefile",
"tests/lib/Makefile"
],
"earliest_patch_date": "2023-12-20 18:03:56-05:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N",
"attackVector": "LOCAL",
"attackComplexity": "LOW",
"privilegesRequired": "LOW",
"userInteraction": "REQUIRED",
"scope": "UNCHANGED",
"confidentialityImpact": "LOW",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 2.8,
"baseSeverity": "LOW"
},
"exploitabilityScore": 1.3,
"impactScore": 1.4
}
},
"cwes": [],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]