[
{
"cve_id": "CVE-2012-4520",
"patch_date": [
"2012-10-17 14:36:41-07:00",
"2012-10-17 14:43:08-07:00",
"2012-10-17 14:40:41-07:00"
],
"patch_files": [
"django/contrib/auth/views.py",
"django/http/__init__.py",
"django/contrib/auth/tests/urls.py",
"django/contrib/auth/tests/views.py"
],
"earliest_patch_date": "2012-10-17 14:36:41-07:00",
"earliest_vuln_date": "2010-12-02 00:43:52+00:00",
"vuln_files": [
"django/contrib/auth/views.py"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 6.4
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 4.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-20"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2013-6044",
"patch_date": [
"2013-08-13 11:00:13-05:00",
"2013-08-13 11:06:22-05:00",
"2013-08-13 11:03:49-05:00"
],
"patch_files": [
"django/utils/http.py",
"django/contrib/auth/tests/test_views.py",
"django/contrib/auth/tests/views.py"
],
"earliest_patch_date": "2013-08-13 11:00:13-05:00",
"earliest_vuln_date": "2010-03-01 19:58:53+00:00",
"vuln_files": [
"django/utils/http.py",
"django/contrib/auth/tests/views.py",
"django/contrib/auth/tests/test_views.py"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 4.3
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"CWE-79"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"django/contrib/auth/tests/views.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2013-4249",
"patch_date": [
"2013-08-13 11:04:21-05:00",
"2013-08-13 11:06:41-05:00"
],
"patch_files": [
"tests/regressiontests/admin_widgets/tests.py",
"django/contrib/admin/widgets.py",
"tests/admin_widgets/tests.py"
],
"earliest_patch_date": "2013-08-13 11:04:21-05:00",
"earliest_vuln_date": "2012-11-03 11:57:33+01:00",
"vuln_files": [
"tests/regressiontests/admin_widgets/tests.py",
"django/contrib/admin/widgets.py",
"tests/admin_widgets/tests.py"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 4.3
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"CWE-79"
],
"fix_duplicate_type": true,
"fix_duplicate_types": [
"CWE-79"
],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2014-0483",
"patch_date": [
"2014-08-20 14:42:48-04:00"
],
"patch_files": [
"django/contrib/admin/options.py",
"django/contrib/admin/views/main.py",
"docs/releases/1.5.9.txt",
"docs/ref/exceptions.txt",
"django/contrib/admin/exceptions.py",
"tests/admin_views/tests.py",
"docs/releases/1.6.6.txt",
"docs/releases/1.4.14.txt"
],
"earliest_patch_date": "2014-08-20 14:42:48-04:00",
"earliest_vuln_date": "2008-09-01 22:43:38+00:00",
"vuln_files": [
"django/contrib/admin/views/main.py",
"django/contrib/admin/options.py",
"tests/admin_views/tests.py"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:S/C:P/I:N/A:N",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "SINGLE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 3.5
},
"severity": "LOW",
"exploitabilityScore": 6.8,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-264"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2015-8213",
"patch_date": [
"2015-11-24 11:20:29-05:00"
],
"patch_files": [
"tests/i18n/tests.py",
"docs/releases/1.7.11.txt",
"docs/releases/1.8.7.txt",
"django/utils/formats.py"
],
"earliest_patch_date": "2015-11-24 11:20:29-05:00",
"earliest_vuln_date": "2015-11-05 09:22:12+01:00",
"vuln_files": [
"docs/releases/1.7.11.txt",
"docs/releases/1.8.7.txt"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-200"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2016-2512",
"patch_date": [
"2016-03-01 11:25:28-05:00"
],
"patch_files": [
"docs/releases/1.8.10.txt",
"django/utils/http.py",
"tests/utils_tests/test_http.py",
"docs/releases/1.9.3.txt"
],
"earliest_patch_date": "2016-03-01 11:25:28-05:00",
"earliest_vuln_date": "2014-05-14 10:19:48+02:00",
"vuln_files": [
"django/utils/http.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.0",
"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "REQUIRED",
"scope": "CHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "HIGH",
"availabilityImpact": "NONE",
"baseScore": 7.4,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 2.8,
"impactScore": 4
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 4.3
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"CWE-79"
],
"fix_duplicate_type": true,
"fix_duplicate_types": [
"CWE-79"
],
"intro_duplicate_type": true,
"intro_duplicated_types": [
"CWE-79"
],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"django/utils/http.py"
],
"file_fixed_before_vuln_again": true,
"files_fixed_before_vuln_again": [
"django/utils/http.py"
]
},
{
"cve_id": "CVE-2016-2513",
"patch_date": [
"2016-03-01 11:25:28-05:00"
],
"patch_files": [
"docs/topics/auth/passwords.txt",
"django/contrib/auth/hashers.py",
"tests/auth_tests/test_hashers.py",
"docs/releases/1.8.10.txt",
"docs/releases/1.9.3.txt"
],
"earliest_patch_date": "2016-03-01 11:25:28-05:00",
"earliest_vuln_date": "2011-12-23 03:53:56+00:00",
"vuln_files": [
"tests/auth_tests/test_hashers.py",
"django/contrib/auth/hashers.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.0",
"vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N",
"attackVector": "NETWORK",
"attackComplexity": "HIGH",
"privilegesRequired": "NONE",
"userInteraction": "REQUIRED",
"scope": "UNCHANGED",
"confidentialityImpact": "LOW",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 3.1,
"baseSeverity": "LOW"
},
"exploitabilityScore": 1.6,
"impactScore": 1.4
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:H/Au:N/C:P/I:N/A:N",
"accessVector": "NETWORK",
"accessComplexity": "HIGH",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 2.6
},
"severity": "LOW",
"exploitabilityScore": 4.9,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"CWE-200"
],
"fix_duplicate_type": true,
"fix_duplicate_types": [
"CWE-200"
],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"docs/releases/1.8.10.txt",
"docs/releases/1.9.3.txt"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2016-6186",
"patch_date": [
"2016-07-15 09:23:32-04:00",
"2016-07-18 13:45:11-04:00"
],
"patch_files": [
"django/views/debug.py",
"tests/admin_views/admin.py",
"django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js",
"tests/admin_views/models.py",
"tests/admin_views/tests.py",
"docs/releases/1.9.8.txt",
"docs/releases/1.8.14.txt"
],
"earliest_patch_date": "2016-07-15 09:23:32-04:00",
"earliest_vuln_date": "2005-11-14 17:44:50+00:00",
"vuln_files": [
"django/views/debug.py",
"docs/releases/1.9.8.txt",
"django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js",
"tests/admin_views/tests.py",
"docs/releases/1.8.14.txt",
"tests/admin_views/admin.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.0",
"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "REQUIRED",
"scope": "CHANGED",
"confidentialityImpact": "LOW",
"integrityImpact": "LOW",
"availabilityImpact": "NONE",
"baseScore": 6.1,
"baseSeverity": "MEDIUM"
},
"exploitabilityScore": 2.8,
"impactScore": 2.7
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 4.3
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 2.9,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"CWE-79"
],
"fix_duplicate_type": true,
"fix_duplicate_types": [
"CWE-79"
],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"tests/admin_views/tests.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2018-7536",
"patch_date": [
"2018-03-01 11:58:41-05:00",
"2018-02-27 13:54:19-05:00",
"2018-03-06 08:52:23-05:00"
],
"patch_files": [
"tests/utils_tests/test_html.py",
"django/utils/html.py",
"docs/releases/1.8.19.txt",
"docs/releases/1.11.11.txt",
"docs/releases/2.0.3.txt"
],
"earliest_patch_date": "2018-02-27 13:54:19-05:00",
"earliest_vuln_date": "2012-01-07 18:39:14+00:00",
"vuln_files": [
"django/utils/html.py",
"tests/utils_tests/test_html.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.0",
"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "NONE",
"availabilityImpact": "LOW",
"baseScore": 5.3,
"baseSeverity": "MEDIUM"
},
"exploitabilityScore": 3.9,
"impactScore": 1.4
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "NONE",
"availabilityImpact": "PARTIAL",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"acInsufInfo": true,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-185"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2020-7471",
"patch_date": [
"2020-02-03 08:49:13+01:00"
],
"patch_files": [
"django/contrib/postgres/aggregates/general.py",
"tests/postgres_tests/test_aggregates.py",
"docs/releases/index.txt",
"django/contrib/postgres/aggregates/mixins.py",
"docs/releases/3.0.3.txt",
"docs/releases/2.2.10.txt",
"docs/releases/1.11.28.txt"
],
"earliest_patch_date": "2020-02-03 08:49:13+01:00",
"earliest_vuln_date": "2018-06-28 20:29:33-04:00",
"vuln_files": [
"django/contrib/postgres/aggregates/general.py",
"django/contrib/postgres/aggregates/mixins.py",
"docs/releases/3.0.3.txt"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 9.8,
"baseSeverity": "CRITICAL"
},
"exploitabilityScore": 3.9,
"impactScore": 5.9
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "PARTIAL",
"baseScore": 7.5
},
"severity": "HIGH",
"exploitabilityScore": 10,
"impactScore": 6.4,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-89"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2021-31542",
"patch_date": [
"2021-04-27 19:10:08+02:00",
"2021-04-27 19:12:15+02:00",
"2021-05-04 08:43:52+02:00"
],
"patch_files": [
"tests/file_storage/test_generate_filename.py",
"docs/releases/2.2.21.txt",
"django/utils/text.py",
"docs/releases/index.txt",
"tests/forms_tests/field_tests/test_filefield.py",
"django/http/multipartparser.py",
"docs/releases/3.2.1.txt",
"django/core/files/storage.py",
"tests/utils_tests/test_text.py",
"django/db/models/fields/files.py",
"tests/file_uploads/tests.py",
"docs/releases/3.1.9.txt",
"django/core/files/uploadedfile.py",
"django/core/files/utils.py"
],
"earliest_patch_date": "2021-04-27 19:10:08+02:00",
"earliest_vuln_date": "2005-07-13 01:25:57+00:00",
"vuln_files": [
"tests/file_storage/test_generate_filename.py",
"django/utils/text.py",
"django/http/multipartparser.py",
"tests/file_uploads/tests.py",
"tests/forms_tests/field_tests/test_filefield.py",
"docs/releases/3.2.1.txt"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-22"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"docs/releases/index.txt"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2021-33571",
"patch_date": [
"2021-06-02 10:26:22+02:00",
"2021-06-02 10:38:07+02:00",
"2021-06-02 10:44:39+02:00"
],
"patch_files": [
"django/core/validators.py",
"tests/validators/invalid_urls.txt",
"tests/validators/tests.py",
"docs/releases/3.2.4.txt",
"docs/releases/2.2.24.txt",
"tests/validators/valid_urls.txt",
"docs/releases/3.1.12.txt"
],
"earliest_patch_date": "2021-06-02 10:26:22+02:00",
"earliest_vuln_date": "2015-01-06 14:04:25-05:00",
"vuln_files": [
"django/core/validators.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "HIGH",
"availabilityImpact": "NONE",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-918"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2022-23833",
"patch_date": [
"2022-02-01 07:57:28+01:00",
"2022-02-01 07:54:17+01:00",
"2022-02-01 07:44:49+01:00"
],
"patch_files": [
"django/http/multipartparser.py",
"docs/releases/3.2.12.txt",
"docs/releases/4.0.2.txt",
"tests/file_uploads/tests.py",
"docs/releases/2.2.27.txt"
],
"earliest_patch_date": "2022-02-01 07:44:49+01:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "NONE",
"availabilityImpact": "HIGH",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "NONE",
"availabilityImpact": "PARTIAL",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-835"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"django/http/multipartparser.py",
"tests/file_uploads/tests.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2022-41323",
"patch_date": [
"2022-09-27 10:17:34+02:00"
],
"patch_files": [
"django/urls/resolvers.py",
"docs/releases/3.2.16.txt",
"tests/i18n/patterns/tests.py"
],
"earliest_patch_date": "2022-09-27 10:17:34+02:00",
"earliest_vuln_date": "2017-09-20 18:04:42-04:00",
"vuln_files": [
"django/urls/resolvers.py",
"docs/releases/3.2.16.txt"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "NONE",
"availabilityImpact": "HIGH",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
}
},
"cwes": [
"NVD-CWE-Other"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]