[
{
"cve_id": "CVE-2021-41247",
"patch_date": [
"2021-11-04 13:21:52+01:00"
],
"patch_files": [
"jupyterhub/singleuser/mixins.py",
"jupyterhub/services/auth.py",
"docs/source/changelog.md"
],
"earliest_patch_date": "2021-11-04 13:21:52+01:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "NONE",
"integrityImpact": "HIGH",
"availabilityImpact": "NONE",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "NONE",
"integrityImpact": "PARTIAL",
"availabilityImpact": "NONE",
"baseScore": 5
},
"severity": "MEDIUM",
"exploitabilityScore": 10,
"impactScore": 2.9,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-613"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2024-28233",
"patch_date": [
"2024-03-20 13:19:29+01:00"
],
"patch_files": [
"jupyterhub/utils.py",
".github/workflows/test.yml",
"jupyterhub/handlers/base.py",
"jupyterhub/_xsrf_utils.py",
"jupyterhub/singleuser/mixins.py",
"docs/source/explanation/websecurity.md",
"jupyterhub/tests/test_api.py",
"docs/source/reference/changelog.md",
"jupyterhub/tests/test_pages.py",
"jupyterhub/tests/browser/test_browser.py",
"jupyterhub/tests/test_services_auth.py",
"jupyterhub/tests/test_singleuser.py",
"jupyterhub/tests/utils.py",
"jupyterhub/tests/mocking.py",
"jupyterhub/services/auth.py",
"jupyterhub/singleuser/extension.py",
"jupyterhub/user.py",
"jupyterhub/spawner.py",
"jupyterhub/app.py",
"jupyterhub/apihandlers/base.py"
],
"earliest_patch_date": "2024-03-20 13:19:29+01:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {},
"cwes": [],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"jupyterhub/singleuser/mixins.py",
"jupyterhub/services/auth.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2024-41942",
"patch_date": [
"2024-07-03 09:18:04+02:00",
"2024-07-02 11:55:54+02:00"
],
"patch_files": [
"jupyterhub/apihandlers/users.py",
"jupyterhub/tests/test_api.py",
"jupyterhub/scopes.py"
],
"earliest_patch_date": "2024-07-02 11:55:54+02:00",
"earliest_vuln_date": "2014-09-14 16:47:09-07:00",
"vuln_files": [
"jupyterhub/apihandlers/users.py",
"jupyterhub/tests/test_api.py",
"jupyterhub/scopes.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "HIGH",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 7.2,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 1.2,
"impactScore": 5.9
}
},
"cwes": [
"NVD-CWE-noinfo"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"jupyterhub/tests/test_api.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]