[
{
"cve_id": "CVE-2022-30767",
"patch_date": [
"2019-09-04 11:37:19-05:00"
],
"patch_files": [
"net/nfs.c"
],
"earliest_patch_date": "2019-09-04 11:37:19-05:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 9.8,
"baseSeverity": "CRITICAL"
},
"exploitabilityScore": 3.9,
"impactScore": 5.9
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "PARTIAL",
"baseScore": 7.5
},
"severity": "HIGH",
"exploitabilityScore": 10,
"impactScore": 6.4,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-120"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2021-27097",
"patch_date": [
"2021-02-15 22:31:53-05:00",
"2021-02-15 22:31:54-05:00",
"2021-02-15 19:17:18-05:00"
],
"patch_files": [
"common/fdt_region.c",
"test/py/tests/test_vboot.py",
"common/Kconfig.boot",
"include/image.h",
"drivers/fpga/socfpga_arria10.c",
"tools/mkimage.h",
"common/image-fit-sig.c",
"cmd/bootm.c",
"common/update.c",
"test/py/tests/vboot_evil.py",
"cmd/source.c",
"tools/fit_common.c",
"test/py/tests/test_fit.py",
"test/py/tests/vboot_forge.py",
"cmd/disk.c",
"tools/fit_image.c",
"cmd/fpga.c",
"cmd/bootefi.c",
"cmd/nand.c",
"drivers/net/fsl-mc/mc.c",
"arch/arm/cpu/armv8/sec_firmware.c",
"common/splash_source.c",
"common/image-fdt.c",
"cmd/ximg.c",
"drivers/net/pfe_eth/pfe_firmware.c",
"common/image-fit.c",
"scripts/dtc/libfdt/fdt_ro.c"
],
"earliest_patch_date": "2021-02-15 19:17:18-05:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
"attackVector": "LOCAL",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "REQUIRED",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 7.8,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 1.8,
"impactScore": 5.9
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "PARTIAL",
"baseScore": 6.8
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 6.4,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"NVD-CWE-noinfo"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2021-27138",
"patch_date": [
"2021-02-15 22:31:54-05:00",
"2021-02-15 19:17:25-05:00",
"2021-02-15 22:31:54-05:00"
],
"patch_files": [
"test/py/tests/test_vboot.py",
"common/fdt_region.c",
"common/Kconfig.boot",
"include/image.h",
"drivers/fpga/socfpga_arria10.c",
"tools/mkimage.h",
"common/image-fit-sig.c",
"cmd/bootm.c",
"common/update.c",
"test/py/tests/vboot_evil.py",
"cmd/source.c",
"tools/fit_common.c",
"test/py/tests/test_fit.py",
"test/py/tests/vboot_forge.py",
"cmd/disk.c",
"tools/fit_image.c",
"cmd/fpga.c",
"cmd/bootefi.c",
"cmd/nand.c",
"drivers/net/fsl-mc/mc.c",
"arch/arm/cpu/armv8/sec_firmware.c",
"common/splash_source.c",
"common/image-fdt.c",
"cmd/ximg.c",
"drivers/net/pfe_eth/pfe_firmware.c",
"common/image-fit.c",
"scripts/dtc/libfdt/fdt_ro.c"
],
"earliest_patch_date": "2021-02-15 19:17:25-05:00",
"earliest_vuln_date": "2013-06-04 16:06:31-04:00",
"vuln_files": [
"test/py/tests/test_vboot.py",
"common/image-fit.c",
"common/image-fit-sig.c",
"test/py/tests/test_fit.py",
"test/py/tests/vboot_forge.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
"attackVector": "LOCAL",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "REQUIRED",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 7.8,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 1.8,
"impactScore": 5.9
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "PARTIAL",
"baseScore": 6.8
},
"severity": "MEDIUM",
"exploitabilityScore": 8.6,
"impactScore": 6.4,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": true
}
},
"cwes": [
"NVD-CWE-noinfo"
],
"fix_duplicate_type": true,
"fix_duplicate_types": [
"NVD-CWE-noinfo"
],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"test/py/tests/test_vboot.py",
"common/fdt_region.c",
"common/Kconfig.boot",
"include/image.h",
"drivers/fpga/socfpga_arria10.c",
"tools/mkimage.h",
"common/image-fit-sig.c",
"cmd/bootm.c",
"common/update.c",
"test/py/tests/vboot_evil.py",
"cmd/source.c",
"tools/fit_common.c",
"test/py/tests/test_fit.py",
"test/py/tests/vboot_forge.py",
"cmd/disk.c",
"tools/fit_image.c",
"cmd/fpga.c",
"cmd/bootefi.c",
"cmd/nand.c",
"drivers/net/fsl-mc/mc.c",
"arch/arm/cpu/armv8/sec_firmware.c",
"common/splash_source.c",
"common/image-fdt.c",
"cmd/ximg.c",
"drivers/net/pfe_eth/pfe_firmware.c",
"common/image-fit.c",
"scripts/dtc/libfdt/fdt_ro.c"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2022-34835",
"patch_date": [
"2022-06-28 15:51:56-04:00"
],
"patch_files": [
"cmd/i2c.c"
],
"earliest_patch_date": "2022-06-28 15:51:56-04:00",
"earliest_vuln_date": "2002-10-26 15:22:42+00:00",
"vuln_files": [
"cmd/i2c.c"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 9.8,
"baseSeverity": "CRITICAL"
},
"exploitabilityScore": 3.9,
"impactScore": 5.9
},
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
"accessVector": "NETWORK",
"accessComplexity": "LOW",
"authentication": "NONE",
"confidentialityImpact": "PARTIAL",
"integrityImpact": "PARTIAL",
"availabilityImpact": "PARTIAL",
"baseScore": 7.5
},
"severity": "HIGH",
"exploitabilityScore": 10,
"impactScore": 6.4,
"acInsufInfo": false,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-787"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]